version: '3.8'

services:
  react-app:
    build:
      context: ./path/to/react-app  # Path to Dockerfile
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  fast-api:
    build:
      context: ./path/to/fast-api  # Path to Dockerfile
      dockerfile: Dockerfile
    ports:
      - "8000:8000"